package com.test.demo.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table commet
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Commet implements Serializable {
    /**
     * Database Column Remarks:
     *   评论id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commet.comment_id
     *
     * @mbg.generated
     */
    private String commentId;

    /**
     * Database Column Remarks:
     *   子评论id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commet.comment_sub_id
     *
     * @mbg.generated
     */
    private String commentSubId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commet.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   评论内容,包括emjo
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commet.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   赞,0 赞， 1不赞
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commet.is_like
     *
     * @mbg.generated
     */
    private Integer isLike;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commet.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   分享id，32位uuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commet.share_id
     *
     * @mbg.generated
     */
    private String shareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commet
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commet.comment_id
     *
     * @return the value of commet.comment_id
     *
     * @mbg.generated
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commet.comment_id
     *
     * @param commentId the value for commet.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commet.comment_sub_id
     *
     * @return the value of commet.comment_sub_id
     *
     * @mbg.generated
     */
    public String getCommentSubId() {
        return commentSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commet.comment_sub_id
     *
     * @param commentSubId the value for commet.comment_sub_id
     *
     * @mbg.generated
     */
    public void setCommentSubId(String commentSubId) {
        this.commentSubId = commentSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commet.create_date
     *
     * @return the value of commet.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commet.create_date
     *
     * @param createDate the value for commet.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commet.content
     *
     * @return the value of commet.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commet.content
     *
     * @param content the value for commet.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commet.is_like
     *
     * @return the value of commet.is_like
     *
     * @mbg.generated
     */
    public Integer getIsLike() {
        return isLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commet.is_like
     *
     * @param isLike the value for commet.is_like
     *
     * @mbg.generated
     */
    public void setIsLike(Integer isLike) {
        this.isLike = isLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commet.user_id
     *
     * @return the value of commet.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commet.user_id
     *
     * @param userId the value for commet.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commet.share_id
     *
     * @return the value of commet.share_id
     *
     * @mbg.generated
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commet.share_id
     *
     * @param shareId the value for commet.share_id
     *
     * @mbg.generated
     */
    public void setShareId(String shareId) {
        this.shareId = shareId;
    }
}