package com.test.demo.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table follow
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Follow implements Serializable {
    /**
     * Database Column Remarks:
     *   关注id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follow_id
     *
     * @mbg.generated
     */
    private String followId;

    /**
     * Database Column Remarks:
     *   被关注人用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.user_followed_id
     *
     * @mbg.generated
     */
    private String userFollowedId;

    /**
     * Database Column Remarks:
     *   关注人用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table follow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follow_id
     *
     * @return the value of follow.follow_id
     *
     * @mbg.generated
     */
    public String getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follow_id
     *
     * @param followId the value for follow.follow_id
     *
     * @mbg.generated
     */
    public void setFollowId(String followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.user_followed_id
     *
     * @return the value of follow.user_followed_id
     *
     * @mbg.generated
     */
    public String getUserFollowedId() {
        return userFollowedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.user_followed_id
     *
     * @param userFollowedId the value for follow.user_followed_id
     *
     * @mbg.generated
     */
    public void setUserFollowedId(String userFollowedId) {
        this.userFollowedId = userFollowedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.user_id
     *
     * @return the value of follow.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.user_id
     *
     * @param userId the value for follow.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}