package com.test.demo.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table share_img
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShareImg implements Serializable {
    /**
     * Database Column Remarks:
     *   图片/视频id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_img.img_id
     *
     * @mbg.generated
     */
    private String imgId;

    /**
     * Database Column Remarks:
     *   分享图片链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_img.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * Database Column Remarks:
     *   图片类型,从0开始
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_img.img_type
     *
     * @mbg.generated
     */
    private Integer imgType;

    /**
     * Database Column Remarks:
     *   播放数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_img.play_count
     *
     * @mbg.generated
     */
    private Integer playCount;

    /**
     * Database Column Remarks:
     *   分享id，32位uuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_img.share_id
     *
     * @mbg.generated
     */
    private String shareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share_img
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_img.img_id
     *
     * @return the value of share_img.img_id
     *
     * @mbg.generated
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_img.img_id
     *
     * @param imgId the value for share_img.img_id
     *
     * @mbg.generated
     */
    public void setImgId(String imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_img.img_url
     *
     * @return the value of share_img.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_img.img_url
     *
     * @param imgUrl the value for share_img.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_img.img_type
     *
     * @return the value of share_img.img_type
     *
     * @mbg.generated
     */
    public Integer getImgType() {
        return imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_img.img_type
     *
     * @param imgType the value for share_img.img_type
     *
     * @mbg.generated
     */
    public void setImgType(Integer imgType) {
        this.imgType = imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_img.play_count
     *
     * @return the value of share_img.play_count
     *
     * @mbg.generated
     */
    public Integer getPlayCount() {
        return playCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_img.play_count
     *
     * @param playCount the value for share_img.play_count
     *
     * @mbg.generated
     */
    public void setPlayCount(Integer playCount) {
        this.playCount = playCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_img.share_id
     *
     * @return the value of share_img.share_id
     *
     * @mbg.generated
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_img.share_id
     *
     * @param shareId the value for share_img.share_id
     *
     * @mbg.generated
     */
    public void setShareId(String shareId) {
        this.shareId = shareId;
    }
}