package com.test.demo.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table share
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Share implements Serializable {
    /**
     * Database Column Remarks:
     *   分享id，32位uuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.share_id
     *
     * @mbg.generated
     */
    private String shareId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   赞,0 不赞， 1赞
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.is_like
     *
     * @mbg.generated
     */
    private Integer isLike;

    /**
     * Database Column Remarks:
     *   收藏，0不收藏，1收藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.is_collect
     *
     * @mbg.generated
     */
    private Integer isCollect;

    /**
     * Database Column Remarks:
     *   阅读数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.read_count
     *
     * @mbg.generated
     */
    private Integer readCount;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share
     *
     * @mbg.generated
     */
    private List<String> imgList;

    public List<String> getImgList() {
        return imgList;
    }

    public void setImgList(List<String> imgList) {
        this.imgList = imgList;
    }

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.share_id
     *
     * @return the value of share.share_id
     *
     * @mbg.generated
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.share_id
     *
     * @param shareId the value for share.share_id
     *
     * @mbg.generated
     */
    public void setShareId(String shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.create_date
     *
     * @return the value of share.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.create_date
     *
     * @param createDate the value for share.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.content
     *
     * @return the value of share.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.content
     *
     * @param content the value for share.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.is_like
     *
     * @return the value of share.is_like
     *
     * @mbg.generated
     */
    public Integer getIsLike() {
        return isLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.is_like
     *
     * @param isLike the value for share.is_like
     *
     * @mbg.generated
     */
    public void setIsLike(Integer isLike) {
        this.isLike = isLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.is_collect
     *
     * @return the value of share.is_collect
     *
     * @mbg.generated
     */
    public Integer getIsCollect() {
        return isCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.is_collect
     *
     * @param isCollect the value for share.is_collect
     *
     * @mbg.generated
     */
    public void setIsCollect(Integer isCollect) {
        this.isCollect = isCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.read_count
     *
     * @return the value of share.read_count
     *
     * @mbg.generated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.read_count
     *
     * @param readCount the value for share.read_count
     *
     * @mbg.generated
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.user_id
     *
     * @return the value of share.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.user_id
     *
     * @param userId the value for share.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}