package com.test.demo.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table share_category
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShareCategory implements Serializable {
    /**
     * Database Column Remarks:
     *   类别id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_category.category_id
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     * Database Column Remarks:
     *   内容类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_category.category_code
     *
     * @mbg.generated
     */
    private String categoryCode;

    /**
     * Database Column Remarks:
     *   内容类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_category.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     * Database Column Remarks:
     *   分享id，32位uuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_category.share_id
     *
     * @mbg.generated
     */
    private String shareId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_category.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share_category
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_category.category_id
     *
     * @return the value of share_category.category_id
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_category.category_id
     *
     * @param categoryId the value for share_category.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_category.category_code
     *
     * @return the value of share_category.category_code
     *
     * @mbg.generated
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_category.category_code
     *
     * @param categoryCode the value for share_category.category_code
     *
     * @mbg.generated
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_category.category_name
     *
     * @return the value of share_category.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_category.category_name
     *
     * @param categoryName the value for share_category.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_category.share_id
     *
     * @return the value of share_category.share_id
     *
     * @mbg.generated
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_category.share_id
     *
     * @param shareId the value for share_category.share_id
     *
     * @mbg.generated
     */
    public void setShareId(String shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_category.user_id
     *
     * @return the value of share_category.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_category.user_id
     *
     * @param userId the value for share_category.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}